### ISSUE TITLE
Wrong photo rotation

### ISSUE THREAD

**Issue by Crysis21** [CameraKit/camerakit-android#10]
I replaced a lot of complicated code I used with CameraKit. While testing the new implementation, I discovered that output photos are rotated 90 degreees clockwise on my Samsung Galaxy S4. Nexus 5 on the other hand, has no problem.

great library, I love it.

**Comment by suomi35** [comment]
I experience this as well, on both Samsung Galaxy S4 (API17) and Galaxy S7 (API24), when `app:ckCropOutput="true"`. The rotation is correct when if cropping is not set (or is false).

**Comment by suomi35** [comment]
I have some more input on this, after spending more time with it.
If I write the byte array directly to a file on disk, without doing any manipulation, that image file does not experience any rotation issues.

However, if I dump the byte array to a bitmap (`BitmapFactory.decodeByteArray()`) the image gets rotated 90 degrees. It also gets rotated 90 degrees if I set `app:ckCropOutput="true"` in XML.

**Comment by android-dataticket** [comment]
for me, rotation is happening on an LG v10, but not a Galaxy Note 5

**Comment by suomi35** [comment]
I have yet to test on many phones, but I have ended up building a listener that extends `OrientationEventListener`. Then, I save a normalized variable of the phone's orientation when a photo is taken (0 degrees/90 degrees/180 degrees/270 degress). Before saving the bitmap to disk, I work out which rotation is needed and feed that into a matrix for a secondary bitmap (overwriting the first one). It's not my favorite way to do things, but seems to work.

```
...
    int rotation = orientationListener.getRememberedOrientation();

    switch(rotation) {
        case 0:
            rotation = 270;
            break;
        case 90:
            rotation = 180;
            break;
        case 180:
            rotation = 90;
            break;
        case 270:
            rotation = 0;
            break;
    }
...
    Matrix matrix = new Matrix();
    matrix.postRotate(rotation);
    bitmap=Bitmap.createBitmap(
        bitmap,
        xOffset,
        0,
        squareImageDimension,
        squareImageDimension,
        matrix,
        false
    );
```

**Comment by snowpong** [comment]
Most likely what is happening is that the returned JPEG data has an Exif  TAG_ORIENTATION set. and BitmapFactory.decodeByteArray(..) does not respect / use that.

I save the data to file, read the Exif orientation from it using ExifInterace, and if it needs rotation I load it into a bitmap, rotate it and compress it again.

**Comment by steveadoo32** [comment]
I went ahead and edited the ExifUtil found [here](https://gist.github.com/9re/1990019). 

```
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Matrix;
import android.os.Build;

public class ExifUtil {

    public static Bitmap decodeBitmapWithRotation(byte[] picture) {
        Bitmap bitmap = BitmapFactory.decodeByteArray(picture, 0, picture.length);
        Matrix matrix = getBitmapRotation(picture);
        return Bitmap.createBitmap(bitmap, 0, 0, bitmap.getWidth(), bitmap.getHeight(), matrix, true);
    }

    public static Matrix getBitmapRotation(byte[] picture) {
        int orientation = 0;
        try {
            orientation = getExifOrientation(new ByteArrayInputStream(picture));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Matrix matrix = new Matrix();
        switch (orientation) {
            case 2:
                matrix.setScale(-1, 1);
                break;
            case 3:
                matrix.setRotate(180);
                break;
            case 4:
                matrix.setRotate(180);
                matrix.postScale(-1, 1);
                break;
            case 5:
                matrix.setRotate(90);
                matrix.postScale(-1, 1);
                break;
            case 6:
                matrix.setRotate(90);
                break;
            case 7:
                matrix.setRotate(-90);
                matrix.postScale(-1, 1);
                break;
            case 8:
                matrix.setRotate(-90);
                break;
        }
        return matrix;
    }

    private static int getExifOrientation(InputStream inputStream) throws IOException {
        int orientation = 1;

        try {
            /**
             * if your are targeting only api level >= 5
             * ExifInterface exif = new ExifInterface(src);
             * orientation = exif.getAttributeInt(ExifInterface.TAG_ORIENTATION, 1);
             */
            if (Build.VERSION.SDK_INT >= 5) {
                Class<?> exifClass = Class.forName("android.media.ExifInterface");
                Constructor<?> exifConstructor = exifClass.getConstructor(new Class[]{InputStream.class});
                Object exifInstance = exifConstructor.newInstance(new Object[]{inputStream});
                Method getAttributeInt = exifClass.getMethod("getAttributeInt", new Class[]{String.class, int.class});
                Field tagOrientationField = exifClass.getField("TAG_ORIENTATION");
                String tagOrientation = (String) tagOrientationField.get(null);
                orientation = (Integer) getAttributeInt.invoke(exifInstance, new Object[]{tagOrientation, 1});
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SecurityException e) {
            e.printStackTrace();
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        } catch (IllegalArgumentException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        }

        return orientation;
    }
}
```

Usage: 

```
    private void onPictureTaken(byte[] picture) {ure);
        imageView.setImageBitmap(result);
    }
```

**Comment by android-dataticket** [comment]
what is odd about this, is my LG devices are not reporting any rotation integer inside the exif

my samsung devices do in fact show the rotation integer inside exif, but they are being properly rotated to begin with and require no modification.

the LG devices need modification, so i have to use a workaround that i do not like at all, but it works for now:

```
String manufacturer = Build.MANUFACTURER;
       if(StringUtils.containsIgnoreCase(manufacturer, "lg")){
           Matrix matrix = new Matrix();
           matrix.setRotate(-90);
           bitmapFile = Bitmap.createBitmap(bitmapFile, 0, 0, bitmapFile.getWidth(), bitmapFile.getHeight(), matrix, true);
       }
```

**Comment by baurine** [comment]
hey guys, can you help to check whether the PR #37 works fine for your phone?

**Comment by bpappin** [comment]
Just an FYI on this issue.
Some devices have the image sensor rotated one way or the other.

**Comment by SeungwookE** [comment]
I got this. 
You guys can fix it with some changing of CameraView code like that.

public void captureImage(final CameraKitEventCallback<CameraKitImage> callback) {
        mCameraImpl.captureImage(new CameraImpl.ImageCapturedCallback() {
            @Override
            public void imageCaptured(byte[] jpeg) {
                PostProcessor postProcessor = new PostProcessor(jpeg);
                postProcessor.setJpegQuality(mJpegQuality);
                postProcessor.setFacing(mFacing);
                if (mCropOutput) {
                    if(getHeight() > getWidth()) // here is point
                        postProcessor.setCropOutput(AspectRatio.of(getHeight(), getWidth())); 
                    else
                        postProcessor.setCropOutput(AspectRatio.of(getWidth(), getHeight()));
                }
                CameraKitImage image = new CameraKitImage(postProcessor.getJpeg());
                if (callback != null) callback.callback(image);
                mEventDispatcher.dispatch(image);
            }
        });
    }
