### ISSUE TITLE
Nexus 5 Ignoring ckMethod

### ISSUE THREAD

**Issue by andrewcking** [CameraKit/camerakit-android#125]
In my own testing I noticed that my Nexus 5 was ignoring my ckMethod setting and only using 'still'. I downloaded the CameraKit demo app and confirmed it also ignores the 'standard' setting there, so app pictures are taken in 1080p as opposed to 8mp. Can anyone else confirm this issue? This is not occurring on my s8.

**Comment by sanidhya26** [comment]
For me its ignoring the ckmethod still..its always using the standard method..
