### ISSUE TITLE
orientation problems

### ISSUE THREAD

**Issue by dongweiq** [CameraKit/camerakit-android#14]
换不同的角度去拍照不能保持照片正向显示，另外，横屏下拍照得到的照片角度也有问题。
For different angles to take pictures can not keep the photo positive display, in addition, the horizontal screen to take pictures of the photo angle is also a problem.

**Comment by andyxialm** [comment]
I have the same problem.

**Comment by baurine** [comment]
hey guys, can you help to check whether the PR #37 works fine for your phone?
