### ISSUE TITLE
Portrait mode having issue 

### ISSUE THREAD

**Issue by vishalpatel1327** [CameraKit/camerakit-android#157]
Hello @dwillmc   I just clone your code   becase i need to change bit rate also 

after your changes of screen orientation at this #111 

What i show that front camera  portrait mode   rotate 180 degree. :( 
but when i used  

> compile 'com.flurgle:camerakit:0.9.18

Its work fine 

![screenshot_2017-08-24-17-54-35](https://user-images.githubusercontent.com/14329287/29666482-16ed788e-88f6-11e7-9c01-b0a8296699ea.png)
![screenshot_2017-08-24-17-57-52](https://user-images.githubusercontent.com/14329287/29666483-1710f71e-88f6-11e7-9321-0bbd7ba6d605.png)

**Comment by Ninjaman494** [comment]
+1 Having the same issue with pulled code. Was working fine with 0.9.18

**Comment by Ninjaman494** [comment]
I found a solution, change the following line in the calculateCaptureRotation method of the Camera1 class:
` return (previewRotation + 2*mDisplayOrientation + 720) %360;`

to:
` return (previewRotation + 2*mDisplayOrientation + 180) %360;`

I've only tested this on my Samsung Galaxy S4, please try it out to see if it works on other devices.
