### ISSUE TITLE
Add stopPreview

### ISSUE THREAD

**Issue by guichico** [CameraKit/camerakit-android#160]
Please add a stop and a startPreview to project

**Comment by akvashi** [comment]
Why was this closed? Doesnt seem to have a reason for this?

**Comment by austinkettner** [comment]
This was closed as it was a stale issue, we hope to include this in our v1.0.0, reOpened as marked as a feature/enhancement

**Comment by emersoncloud** [comment]
@guichico Is there a specific use case you need a startPreview and stopPreview methods for? They are currently only called internally from the `CameraKitView.onResume()` and `CamearKitView.onPause()` methods. Let me know if you need more functionality than this. 

Closing the issue but will reopen if there is still a need for this feature! =)

**Comment by emersoncloud** [comment]
I was mistaken, we do have the ability to start and stop the preview through the `getPreviewListener()` method. The structure may change in upcoming releases but we will let you know if it does!
