### ISSUE TITLE
Demo video?

### ISSUE THREAD

**Issue by Shivang44** [CameraKit/camerakit-android#17]
Maybe I just haven't figured out how to use the demo properly, but why doesn't the demo showcase the video capture capabilities of this library?

**Comment by movAX13h** [comment]
I just had the same question and figured it out. The button for video capturing is in the xml. You can remove android:visibility="gone" and set android:weightSum to 4 in the parent linear layout to enable the video button. I've noticed that the app crashes in the emulator when the video button is clicked but it works on a real device.
