### ISSUE TITLE
Distortion in video recording

### ISSUE THREAD

**Issue by sanidhya26** [CameraKit/camerakit-android#174]
In some of the devices, the recorded video is squeezed..Please help

**Comment by sanidhya26** [comment]
has anyone else got this issue?

**Comment by jamolkhon** [comment]
Yes it also gets stretched for me.

**Comment by devingDev** [comment]
I added the CameraKitView to a linearlayout which was added to a fragment page in a tabbed activity.

1. It looks stretched on the screen
2. When recordin it looks also weirdly stretched.
3. When viewing the file afterwards it also looks weird.

Tested video capture with normal camera app on android and it was not stretched.
