### ISSUE TITLE
could you add a onFrameData callback in CameraListener?

### ISSUE THREAD

**Issue by leaf918** [CameraKit/camerakit-android#176]
the frame data is important for realtime frame data processing.
thanks.

**Comment by MrOnyszko** [comment]
I agree with that idea :)

**Comment by dwillmc** [comment]
This is in the works now and coming soon. I want to do a bit on top of just passing the frame though. I've been adding a lot of NDK stuff lately to speed up processing and I'd like to structure that to be usable by CameraKit users. Especially with the frame callbacks where performance is incredibly important.

What sorts of things do you need to do with the frames?

**Comment by sksar** [comment]
@dwillmc 
Possibly a support for a function where we could specify a frame processor function that gets each frame, and also the processed frame (maybe like color enhanced, filter effects) is returned to the camera View.....

**Comment by morejump** [comment]
in my case, i want to  get each frame to use for JNI with opencv c++, and return preview!

**Comment by leaf918** [comment]
@dwillmc In my case ,I have a lot of neural networks for real-time image processing，such as AR,robot vision

**Comment by xymelon** [comment]
@dwillmc In my case, I need frame to use for real-time OCR.

**Comment by monatis** [comment]
@dwillmc In my case, I'm trying to detect motion (i.e., page turns) and take a photo for an automatic scan app.

**Comment by benjaminbarbe** [comment]
Do you have any update on this?

**Comment by austinkettner** [comment]
@xymelon @monatis @benjaminbarbe Yes we plan to have this included in 1.0.0 release aimed for Jan 1, 2018. We hope to open a PR and Snapshot builds for this release, this week so you can comment, test, etc!

@dwillmc May have further input too

**Comment by browningweb** [comment]
Do you have any update on this...? @dwillmc

**Comment by austinkettner** [comment]
We are hoping to issue a 1.0.0 PR soon for testing and a lot of this is included. @browningweb

**Comment by edwardotis** [comment]
@austinkettner Can you post a link here to the PR and/or feature docs? This github issue gets high SEO for the topic.

**Comment by eviansplash** [comment]
BUMP......? should we switch camera package from camerakit...?

**Comment by austinkettner** [comment]
@eviansplash @kunaldawn @edwardotis Here is the 1.0.0 PR: https://github.com/CameraKit/camerakit-android/pull/318 give it a try and let us know a bit more about your use case? We are adding in additional calls ahead of merging and can specifically address this.
