### ISSUE TITLE
Camera preview stretches sometimes

### ISSUE THREAD

**Issue by developer--** [CameraKit/camerakit-android#227]
At first thanks for awesome library.

I had a problem, when app is running sometimes preview is stretched automatically, but if I capture a photo it takes correct scaled picture and than preview is correct.

Tested it on Lenovo and HTC; OS v 6.0.1

![image](https://user-images.githubusercontent.com/7534778/32213943-bab673d8-be36-11e7-94ca-7685e126dbf3.png)

**Comment by dc297** [comment]
I am also facing this issue. Tried on Android 7.1.2 on Oneplus one. It happens randomly though.

**Comment by tartacutza** [comment]
If you have autorotate on it will initialize with the phone's sensor values at creation. If you take a photo or rotate the phone it will recreate with the good values and not stretched. At least this is the conclusion I've reached.

**Comment by devoma** [comment]
I have the same problem. When I start to record the video is stretched and after recording it becomes correct. 
Device: LG K8.  Android 6.0. 
And I noticed something. I tried another [CameraView](https://github.com/natario1/CameraView) library. There if the video quality is set to Lowest or 480p, then it is stretched like here, and if you put other qualities, it works correctly!
Maybe this information will help to understand the problem

**Comment by austinkettner** [comment]
You can expect fixes here in the next few days and they will be instantly available via SNAPSHOT builds of 0.13.0!

**Comment by jamolkhon** [comment]
Any update on this? Can't find any snapshot versions.

**Comment by devoma** [comment]
Have you fixed this bug?

**Comment by frostblooded** [comment]
Seems like this bug occurs always if the screen orientation is portrait, but the preview looks fine when the orientation is landscape.

**Comment by austinkettner** [comment]
Resolved in our 1.0.0 https://github.com/CameraKit/camerakit-android/pull/318 -- please test it out using the notes in the PR and comment in the PR if you see any further issues on any devices!
