### ISSUE TITLE
Change Audio bitrate

### ISSUE THREAD

**Issue by athomaj** [CameraKit/camerakit-android#238]
I am able to change the video bitrate, but not the audio one, is this gonna be possible anytime soon?

**Comment by austinkettner** [comment]
We will get this in our 0.13.0 release, which is our November release! Once it's available in the snapshot builds, I will let you know!

**Comment by emersoncloud** [comment]
This issue will be covered in the upcoming 1.0.0 video release. Closing this issue. If you are having more issues with audio bitrate I will make a new 1.0.0 issue to track it!
