### ISSUE TITLE
Square Video Capturing

### ISSUE THREAD

**Issue by devoma** [CameraKit/camerakit-android#247]
Cool library. But I had a question. 

How to record square video using this library as in instagram?

**Comment by calebdre** [comment]
Isn't the video already a square?  If you want the height to change, you can make sure to constrict the height of `CameraView` when adding it to your layout.

**Comment by Brianvdb** [comment]
@calebdre the output video File is not cropped.

**Comment by Aks-4125** [comment]
@calebdre  square video output is supported at this moment?

**Comment by emersoncloud** [comment]
This is a good feature to consider for future video builds of CameraKit. I will close this ticket and add it to our feature backlog.
