### ISSUE TITLE
CameraListener is not being called if video is recorded from thread other than main thread.

### ISSUE THREAD

**Issue by pranav-margino** [CameraKit/camerakit-android#254]
in MainActivity I have;
cameraView.setCameraListener(new CameraListener() {
            @Override
            public void onVideoTaken(File video) {
                super.onVideoTaken(video);
                Log.d("video", "taken");
                Log.d("path", video.getAbsolutePath());                
                previewPath = video.getAbsolutePath();
                Uri uri = Uri.parse(video.getAbsolutePath());
                videoView.setVideoURI(uri);
                videoView.start();
            }
        });

I intend to run recording process on a separate thread; therefore

btnToggleRecording.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (!isRecording && cameraView != null) {

                    recordingThread = new Thread(new RecordVideoRunnable(cameraView));
                    recordingThread.start();
                    runOnUiThread(updateDuration);
                    btnToggleRecording.setText(getString(R.string.camera_stop_recording));
                } else {
        
                    if(recordingThread!=null){
                        try {
                            recordingThread.join();
                        }catch (InterruptedException e){
                            e.printStackTrace();
                        }

                    }

                    handler.removeCallbacks(updateDuration);
                    btnToggleRecording.setText(getString(R.string.camera_start_recording));
                }
                isRecording = !isRecording;
            }
        });

My runnable is defined as

private class RecordVideoRunnable implements Runnable {
        CameraView cameraView;

        public RecordVideoRunnable(CameraView cameraView) {
            this.cameraView = cameraView;
        }

        @Override
        public void run() {
            this.cameraView.startRecordingVideo();
        }

        public void stop() {
            Log.d("askin", "to stop");
            if (this.cameraView == null) {
                Log.d("camera", "null");
            } else {
                Log.d("camera", "not null");
                this.cameraView.stopRecordingVideo();
            }

        }
    }

**Issue: on thread join, cameraListener is not being called.**

**Comment by emersoncloud** [comment]
This issue has been resolved in 1.0.0 of CameraKit. Closing this issue. If you have further listener issues I will create a new ticket for tracking!
