### ISSUE TITLE
Specify Video Output File

### ISSUE THREAD

**Issue by Brianvdb** [CameraKit/camerakit-android#255]
There currently is no way to set the output video file. I'd like to use my own location.

**Comment by jamolkhon** [comment]
Same problem here. Currently I'm immediately renaming/moving after recording is completed.

**Comment by jamolkhon** [comment]
#64

**Comment by emersoncloud** [comment]
Hey guys we've created a new ticket to track this issue #336. It's currently set for milestone 1.1.0. Comment there if you have any other questions, thanks!
