### ISSUE TITLE
Crash when called 'stop' after 'start'.

### ISSUE THREAD

**Issue by xymelon** [CameraKit/camerakit-android#258]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

Yes

### Environment

Most Phones.

### Steps to Reproduce

(Write your steps here:)

1. Call 'CameraView start()', and it will run in 'CameraViewWorker' thread;
2. Call 'stop', and it will run in another thread, maybe UI thread;
3. When 'CameraViewWorker' thread executes the code in ['Camera1' which  line number is 118](https://github.com/wonderkiln/CameraKit-Android/blob/master/camerakit/src/main/api16/com/wonderkiln/camerakit/Camera1.java#L118), and switch to UI thread executes 'stop' method, it will release 'mCamera'.
4. Finally, when 'CameraViewWorker' continues to execute ['setupPreview()'](https://github.com/wonderkiln/CameraKit-Android/blob/master/camerakit/src/main/api16/com/wonderkiln/camerakit/Camera1.java#L120), it will crash.

### Actual Behavior

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.reconnect()' on a null object reference.

**Comment by emersoncloud** [comment]
This issue has been resolved in 1.0.0 of CameraKit. Let me know if you experience any similar crashes in our latest release!
