### ISSUE TITLE
Recorded video with a different ratio that the Preview

### ISSUE THREAD

**Issue by carrotow** [CameraKit/camerakit-android#263]
### Is this a bug report?

Yes
 
### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

Yes

### Environment

Probably all phones.

### Steps to Reproduce

1. Record a video
2. Show video in preview activity or gallery

### Expected Behavior

The video should have the same ratio/dimension that the preview that was shown to the user.

### Actual Behavior

The recorded video is taller than the preview. There is an extra 
content/space at the top and the bottom that was not visible when i was recording.

**Comment by austinkettner** [comment]
Hi @carrotow can you please update this ticket to follow the guidelines for issues? Happy to look into this once updated!

**Comment by emersoncloud** [comment]
Video support is coming with release 1.0.0 very shortly. We will continue to add video features in later releases. I've created a new ticket to track this feature here: #387.
