### ISSUE TITLE
Video -Path  -Name

### ISSUE THREAD

**Issue by gh7800** [CameraKit/camerakit-android#265]
startvideo:
		mCameraView.captureVideo();
stopvideo:
              mCameraView.stopVideo();
I
Hope that you can customize the name and path

**Comment by georgeRCluj** [comment]
@gh7800, did you find out how to effectively capture the video? what method to use? Since the documentation is outdated http://docs.camerakit.website/#/?id=capturing-video

**Comment by gh7800** [comment]
ok!

**Comment by georgeRCluj** [comment]
ok? that was a question :)

**Comment by emersoncloud** [comment]
Hey @gh7800 sorry this issue slipped through the cracks. We have a ticket open for the v1.1.0 milestone to determine the save location. I just added a comment to make sure we add support to set the filename as well. See it here: #336.

**Comment by emersoncloud** [comment]
@georgeRCluj Thanks for your interest in CameraKit, and I apologize for the outdated docs. We have been hard at work on release v1.0.0 #318. When the official release is out, we will update all the documentation to match. Expect that in the next couple weeks. Thanks!
