### ISSUE TITLE
why flash-light doesn't works if method type is STEEL ?

### ISSUE THREAD

**Issue by developer--** [CameraKit/camerakit-android#266]
OS -> 6.0.0 Lenovo 
OS -> 5.0.0 Samsung

also tested it from playstore app

**Comment by developer--** [comment]
Also cloned repository and tried flash but same issue

**Comment by inder243** [comment]
i am also getting flash issue in STEEL mode
if it is fixed,please let me know the version and Class
i am using 0.13.1

**Comment by emersoncloud** [comment]
This issue will be resolved with the 1.0.0 release including video support. Closing this issue. If you still have flash issues with the latest release create a new ticket and we will investigate =)
