### ISSUE TITLE
Why captured bitmap is so big? more than 30MB

### ISSUE THREAD

**Issue by developer--** [CameraKit/camerakit-android#272]
when capture method is standard bitmap size is more than 30 MB tested on two device OS version 5.0 and 6.0

if method is steel bitmap size is about 18 MB.

problem is that it needs about 3-4 second for image capture

**Comment by xymelon** [comment]
Because the preview size and picture size is so big. So I change the get preview size method, and return preview size that closest to screen size.

`
            while (descendingSizes.hasNext()) {
                size = descendingSizes.next();
                if (targetRatio == null) {
                    mPreviewSize = size;
                    break;
                }
                if (targetRatio.matches(size)) {
                    //return 'preview size' that closest to screen size.
                    if (size.getWidth() >= CameraKit.Internal.screenHeight
                            && size.getHeight() >= CameraKit.Internal.screenWidth) {
                        mPreviewSize = size;
                    } else {
                        if (mPreviewSize == null) {
                            mPreviewSize = size;
                        }
                        break;
                    }
                }
            }
`

**Comment by emersoncloud** [comment]
@xymelon thanks for clearing this up. Closing this issue.
