### ISSUE TITLE
引入cmake后，导致原来的项目中ndk-build生成的so文件无法加载

### ISSUE THREAD

**Issue by liyanmei** [CameraKit/camerakit-android#277]
原来是用jni生成的so文件，然后放在libs/armeabi下面，没有集成该库项目的时候，不报错，集成camerakit项目后，项目中System.loadLibrary("adas1080p");一直报错，显示错误如下：

`12-08 15:27:10.625 1805-2490/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
12-08 15:28:16.435 1089-1252/? E/GpsXtraDownloader: No XTRA servers were specified in the GPS configuration
12-08 15:29:28.135 12260-12260/? E/dalvikvm: /system/framework/am.jar odex has stale dependencies
12-08 15:29:28.815 12273-12273/com.lym.cameraLine E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
12-08 15:29:29.865 12273-12294/com.lym.cameraLine E/HardwareControler: HardwareControler ibrary not found!
12-08 15:29:29.865 12273-12294/com.lym.cameraLine E/HardwareControler: java.lang.UnsatisfiedLinkError: Couldn't load adas1080p from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.lym.cameraLine-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.lym.cameraLine-2, /vendor/lib, /system/lib]]]: findLibrary returned null
12-08 15:29:29.865 5700-5710/? E/KLO_Package: klo_get_package_version: Unable to create temp file!
12-08 15:29:29.865 12273-12294/com.lym.cameraLine E/AndroidRuntime: FATAL EXCEPTION: Thread-6649
                                                                    Process: com.lym.cameraLine, PID: 12273
                                                                    java.lang.UnsatisfiedLinkError: Native method not found: com.adas.adas1080p.init:()I
                                                                        at com.adas.adas1080p.init(Native Method)
                                                                        at com.lym.cameraLine.CameraLibActivity$1.run(CameraLibActivity.java:68)
12-08 15:29:29.915 5700-5710/? E/KLO_Stability: get trace info from /data/system/dropbox/data_app_crash@1512718169931.txt failed`

跪求解决方案。。。。。

**Comment by austinkettner** [comment]
This shouldn't be an error in #318 - let me know if the issue persists
