### ISSUE TITLE
Capturing video issues

### ISSUE THREAD

**Issue by georgeRCluj** [CameraKit/camerakit-android#283]
I cannot figure out how to record a video. I am using the http://docs.camerakit.website/#/?id=capturing-video which is out-dated.

I have a button and when it starts recording I am writing `layoutUi.camera.captureVideo();` then when pressing button again I am writing `layoutUi.camera.stopVideo();` but when I am using the callback
`layoutUi.camera.captureVideo(new CameraKitEventCallback<CameraKitVideo>() {
                @Override
                public void callback(CameraKitVideo cameraKitVideo) {
                    videoFile = cameraKitVideo.getVideoFile();
                    Toast.makeText(thisContext, "finished recording video", Toast.LENGTH_SHORT).show();
                }
            });`

it is not working, the Toast does not appear. Can anybody help on this one?

**Comment by boranyldrm** [comment]
Please look at [this comment on similar issue](https://github.com/wonderkiln/CameraKit-Android/issues/229#issuecomment-344139411). It was helped to me.

**Comment by georgeRCluj** [comment]
Permission to storage is granted, but that method does not work. The callback is not called.

**Comment by georgeRCluj** [comment]
Great, I found it out finally two days ago and used those overrides ;)
Thanks! ;)

2017-12-14 21:10 GMT+02:00 Boran <notifications@github.com>:

**Comment by amitsharma492** [comment]
@georgeRCluj I am facing the same issue. Can you help regarding this?

**Comment by georgeRCluj** [comment]
@amitsharma492, did you manage to find a solution? Otherwise I will write you how I did and it worked absolutely great!

**Comment by austinkettner** [comment]
@georgeRCluj an example would be appreciated, we can include some additional documentation about this in the documentation site. Additionally, we would appreciate if anyone can test out the 1.0.0 PR for issues like this and comment.

**Comment by valterh4ck3r** [comment]
Same issue

**Comment by Joseph82** [comment]
Same issue here!

**Comment by emersoncloud** [comment]
We are adding more robust video support very soon to 1.0.0. Keep an eye on #318 for more information!
