### ISSUE TITLE
How to disable recording audio and only to record video?

### ISSUE THREAD

**Issue by tzzen93** [CameraKit/camerakit-android#286]
I don't know not to disable recording audio. I want to record only video. So, How can I do that? Thanks in advance!

**Comment by cuilongzhe** [comment]
any update on this?

**Comment by austinkettner** [comment]
Hey @cuilongzhe we are working on this as part of 1.x releases. I have added this to the Milestone 1.1.0 and we will keep you posted along the way.

**Comment by emersoncloud** [comment]
Duplicate of #334
