### ISSUE TITLE
onVideo vs videoCaptured not work in xiaomi

### ISSUE THREAD

**Issue by chanmyaethu-mn** [CameraKit/camerakit-android#287]
I am using this in my app video capture function. It works fine in Oneplus but not ok in xiaomi.
Could you please give me any suggestion?
I have followed my code below.

@Override
            public void onVideo(CameraKitVideo cameraKitVideo) {

                if (LaunchCameraActivity.this.isStopByUser) {
                    return;
                }

                File cameraKitVideoFile = cameraKitVideo.getVideoFile();
                File localFile = new File(LaunchCameraActivity.this.mMoviePath);
                if (cameraKitVideoFile.renameTo(localFile)) {
                    Intent intent = new Intent();
                    Bundle localBundle = new Bundle();
                    localBundle.putString(Constants.MOVIE_PATH_KEY, localFile.getAbsolutePath());
                    intent.putExtras(localBundle);
                    LaunchCameraActivity.this.setResult(Constants.RESULT_OK, intent);
                }
                LaunchCameraActivity.this.finish();
            }

**Comment by emersoncloud** [comment]
Hi @chanmyaethu-mn can you test this on the latest release 1.0.0? You can see implementation notes here #318. I'll reopen this issue if you are still having trouble!
