### ISSUE TITLE
Preview is distorted when screen launch with portrait and then change to landscape 

### ISSUE THREAD

**Issue by tzzen93** [CameraKit/camerakit-android#294]
The camera is distorted when screen launch with portrait and then change to landscape orientation immediately. At that timing, the camera is distorted in version com.wonderkiln:camerakit:0.13.1. Thank you very much!

**Comment by xp-vit** [comment]
I think this is a duplicate of: https://github.com/wonderkiln/CameraKit-Android/issues/288

**Comment by Danm72** [comment]
I'm seeing this too.

**Comment by Danm72** [comment]
Was forced to lock orientations.

**Comment by austinkettner** [comment]
Should be resolved in #318 can you please test that out and I will reOpen this if you comment that it is still an issue.

**Comment by jatin-lakhani** [comment]
+1 Its still exist with version 0.13.1
Any workaround on this?

**Comment by emersoncloud** [comment]
@jatin-lakhani There is not currently a workaround in version 0.13.1. The issue should be resolved in v1.0.0 which is currently in review, #318. Try out 1.0.0 and let me know if you are running into the same issues.

**Comment by jatin-lakhani** [comment]
Thank you for the reply! Version 1.0.0 is quite better but video integration seems not integrated yet. Is there any alternative I can use both feature camera capture + video recording?

**Comment by emersoncloud** [comment]
@jatin-lakhani Not yet. We expect to have video support in 1.0.0 this week!

**Comment by fearenales** [comment]
@emersoncloud sorry for necrobumping this issue, but is video already supported in 1.0.0? If not, any idea when it should be available and when 1.0.0 will be released?
