### ISSUE TITLE
Is there a way to access the SurfaceView of the CameraView?

### ISSUE THREAD

**Issue by DeanEncoded** [CameraKit/camerakit-android#298]
I'm trying to add a QR Reader together with CameraKit. 
But I need to get the SurfaceHolder being used by the CameraView  in order to make the reader work.

Is there any chance this is possible?

**Comment by emersoncloud** [comment]
Currently there is not a way to directly access the SurfaceHolder from CameraKit. We will add this to our feature backlog and if there is enough support we will roll it out in a future release. Feel free to dig into the code and add your own method to access the SurfaceHolder and we'd love to take a look!
