### ISSUE TITLE
quickly click facingButton,the app will ANR

### ISSUE THREAD

**Issue by cxmmxc** [CameraKit/camerakit-android#303]
### Is this a bug report?

(YES)

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

(yes.)

### Environment
XiaomiNote Android 6.0.1

### Steps to Reproduce

(Write your steps here:)

1.Run the demo in XiaomiNote
2.quick click the facingButton
3.it is ANR
-----------------I use your demo, so ....    ------------------------
### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by emersoncloud** [comment]
Hi @cxmmxc I haven't been able to reproduce this issue on my own. Could you post a video or screenshots of what's happening? The logcat output would also be helpful to diagnose. I'll reOpen this issue once you have. Thanks!
