### ISSUE TITLE
Compatible with Android pad bug.

### ISSUE THREAD

**Issue by youyuanme** [CameraKit/camerakit-android#308]
![832313327251360552](https://user-images.githubusercontent.com/11382521/35268495-411c5ff4-0064-11e8-91ca-16f79163d78d.png)
android pad 4.2.2

![1](https://user-images.githubusercontent.com/11382521/35269177-47f97ab2-0066-11e8-97df-60f143c2aa6d.jpg)

![2](https://user-images.githubusercontent.com/11382521/35269188-4c955d48-0066-11e8-98f4-15d129210c58.jpg)

![3](https://user-images.githubusercontent.com/11382521/35269282-861d525a-0066-11e8-9b26-8975fcf3d134.jpg)

![305779059456080183](https://user-images.githubusercontent.com/11382521/35269345-ac3fb0e0-0066-11e8-9c24-1e94f4f63356.jpg)
The pad's rear camera screen has always been green, with no screen.It's normal to switch to the front camera.

**Comment by banxxi** [comment]
Have you found any solution for this, happens to me in Samsung galaxy s4

**Comment by chrbien** [comment]
Happens to a customer of mine as well, also on S4. Any solution yet?

**Comment by emersoncloud** [comment]
@youyuanme Could you post a comment following our issue template? I'm having trouble understanding the expected behavior here.
