### ISSUE TITLE
Failed to resolve: com.wonderkiln:camerakit:0.13.1

### ISSUE THREAD

**Issue by fcafra** [CameraKit/camerakit-android#309]
I have added     
compile 'com.wonderkiln:camerakit:0.13.1' into build.gradle (App) but i have this error 
Failed to resolve: com.wonderkiln:camerakit:0.13.1

What am i doing wrong ?

**Comment by austinkettner** [comment]
@fcafra You aren't doing anything wrong, we are clearing up final issues with Bintray and the above will then work. Will update this ticket soon for you.

**Comment by fcafra** [comment]
good news, thanks ...  I wait   :-)

**Comment by EduardoDornel** [comment]
I have same problem

**Comment by shripal17** [comment]
When will it be live back again?

**Comment by dwillmc** [comment]
Working out an issue with JCenter Bintray.
For the time being can all please use the repository directly if it's not working.

In your project level build.gradle you'll see a block that looks something like:

```
allprojects {
    repositories {
        jcenter()
        maven { url 'https://camerakit.bintray.com/camerakit-android-prereleases' }
    }
}
```

Just add the 2nd repository, `maven { url 'https://camerakit.bintray.com/camerakit-android-prereleases' }`

**Comment by urschrei** [comment]
@dwillmc That doesn't resolve the sync error, unfortunately.

**Comment by dwillmc** [comment]
What version are you trying to resolve?

**Comment by urschrei** [comment]
@dwillmc Just tried again, and it's synced. Sorry about that!

**Comment by mjmotani** [comment]
Try to sync with above way getting this issue
`Error:Could not create service of type TaskArtifactStateRepository using TaskExecutionServices.createTaskArtifactStateRepository().
> Unexpected lock protocol found in lock file. Expected 3, found 0.`

**Comment by austinkettner** [comment]
This should all be cleared up now. Let me know if you run into any other issues resolving the desired package version.

**Comment by fcafra** [comment]
@dwillmc  @austinkettner  Thanks

**Comment by caleb-allen** [comment]
Could we get some clarification on http://docs.camerakit.website for which version we should be using?

Docs site shows `0.12.0`, master README shows `0.13.1`

**Comment by austinkettner** [comment]
Latest is always shown in the README, so currently `0.13.1` we have some big documentation updates coming soon.

**Comment by caleb-allen** [comment]
Awesome! Looking forward to it

**Comment by NareshG-Lepton** [comment]
Could not find com.wonderkiln:camerakit:0.13.1. Required by Pix

Can anyone help on it.

**Comment by jzhw0130** [comment]
Could not find com.wonderkiln:camerakit:0.13.5. 
Worked well before, stopped working now.
Can anyone help on it?

**Comment by gauranggoda** [comment]
> For the time being can all please use the repository directly if it's not working.

same issue, if possible can anyone suggest alternate of this library?
`implementation 'com.wonderkiln:camerakit:0.13.1'`

**Comment by deebashd** [comment]
Any update on this?

**Comment by zubaer190** [comment]
Could not find com.wonderkiln:camerakit:0.13.4
any update on this issue?
.

**Comment by stefanbildl** [comment]
Can you please publish to mavenCentral?

**Comment by NareshG-Lepton** [comment]
waiting for long time
