### ISSUE TITLE
Custom video file not returned in VideoCapturedCallback

### ISSUE THREAD

**Issue by jlmcdonnell** [CameraKit/camerakit-android#313]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

Yes

### Environment

CameraKit 0.13.2

### Steps to Reproduce

1. Start recording a video using `CameraView#captureVideo(File, VideoCapturedCallback)`
2. Stop recording

### Expected Behavior

The video file passed in for Step 1 should be provided in `VideoCapturedCallback#videoCaptured`

### Actual Behavior

An unrelated `File` is returned from `Camera1#getVideoFile`

**Comment by emersoncloud** [comment]
We are in the process of revamping video recording for the 1.0.0 release. You can expect that in the coming days. I'll make sure this is covered in that release. If not feel free to leave a comment and I'll reopen the issue!
