### ISSUE TITLE
How to remove the sawtooth

### ISSUE THREAD

**Issue by yangzhenqi** [CameraKit/camerakit-android#319]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

Yes

### Environment
macOS,AndroidStudio3.0,CameraKit 0.13.2

### Steps to Reproduce

1.`ckPinchToZoom="true"`
2.Increase the focal length of the camera

### Expected Behavior

Normal Preview

### Actual Behavior

Sawtooth appears

**Comment by austinkettner** [comment]
Hi @yangzhenqi can you please update this ticket to reflect our Issue Template? Once updated I can reOpen this!

**Comment by yangzhenqi** [comment]
@austinkettner Please open it again. Thank you.

**Comment by austinkettner** [comment]
ReOpened 👍

**Comment by emersoncloud** [comment]
This issue has been resolved in the latest release of 1.0.0-beta1. If you are still experiences any problems drop us a comment and we can dig into it!
