### ISSUE TITLE
Continuous video flash and video recording advanced customizability

### ISSUE THREAD

**Issue by shoomkloom** [CameraKit/camerakit-android#32]
Hey,

It would be great if:
1. Flash on in video recording would switch the flash on continuously.
2. It would be possible to set bitrate, frame rate, quality for video recording.

Thanks!
Oren

**Comment by dwillmc** [comment]
Both are coming very soon!

**Comment by zbobyuan** [comment]
awesome, do you have a plan to implement built-in pinch to zoom?

**Comment by austinkettner** [comment]
@zbobyuan just implemented pinch to zoom here: https://github.com/wonderkiln/CameraKit-Android/tree/release/0.13.0 available via `compile 'com.wonderkiln:camerakit:0.13.0-Snapshot'
