### ISSUE TITLE
Create new istance without preview

### ISSUE THREAD

**Issue by daniele93dc** [CameraKit/camerakit-android#322]
### Is this a bug report?

Yes 

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

Yes

### Steps to Reproduce

(Write your steps here:)

1. Create a new CameraView instance with cameraview = new CameraView(this)
2. start camera
3. take a photo

### Expected Behavior

get a photo

### Actual Behavior

Crash error: FATAL EXCEPTION: CameraViewWorker
after onImage event the app crash

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by valterh4ck3r** [comment]
What your device ?  manufacturer and model ?

**Comment by daniele93dc** [comment]
Galaxy s5 and Asus Zenfone

**Comment by austinkettner** [comment]
Can you also outline what version of CameraKit you are using here?

**Comment by daniele93dc** [comment]
both 0.13.2 and 1.0.0

**Comment by daniele93dc** [comment]
any news?

**Comment by daniele93dc** [comment]
There are any news with new version for this?

**Comment by emersoncloud** [comment]
@daniele93dc thanks for following up with this. It is not currently possible to create an instance from a service like the use case you mentioned. We will review this internally and add it to our milestones for future releases if we get enough interest! 

Our current focus has been delivering core camera functionality for 1.0.0!
