### ISSUE TITLE
Selfie Screen flash not working - samsung s8+

### ISSUE THREAD

**Issue by aravindhkumar23** [CameraKit/camerakit-android#325]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

Yes

### Environment

com.wonderkiln:camerakit:0.11.2

### Actual Behavior
 **Selfie screen flash is not working,** it works with normal flash(both front and back).
but some devices are provided with screen flash which is not working when the flash is enabled.

Tested in OnePlus-5, Samsung s8+

my xml code:
`<com.wonderkiln.camerakit.CameraView
            android:id="@+id/camera"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:adjustViewBounds="true"
            app:ckZoom="pinch"
            app:ckFocus="tapWithMarker"
            app:ckPermissions="picture"
            android:background="@color/colorGray"
            />`

**Comment by KRNareshKumar** [comment]
I am also facing a similar issue , where normal flash works fine but Screen flash is not working.

Could you provide with an update if there is any workarounds I can use to get over it.

Thanks in advance.

**Comment by emersoncloud** [comment]
Can you test on our latest version 1.0.0-beta1 #318 and report back if you are still experiencing issues? I'll reopen this ticket if they still exist. Thanks! =)
