### ISSUE TITLE
HOW Can I set Exposure of Camera???

### ISSUE THREAD

**Issue by ash3734** [CameraKit/camerakit-android#327]
### Is this a bug report?

NO

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

YES

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by austinkettner** [comment]
Hi Ash, can you please fill in the appropriate issue template or describe your question in greater detail? We will then open this back and up and assign it proper labels!
