### ISSUE TITLE
Black camera preview as soon as 'Allow' is clicked (new permissions)

### ISSUE THREAD

**Issue by Zarkopafilis** [CameraKit/camerakit-android#331]
### Is this a bug report?
Yes
(Maybe)

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

Yes

### Environment
Nexus 6p API 25 on android studio emulator 

### Steps to Reproduce

Just add a camera view and set managing permissions 

(Write your steps here:)

1. Add camera view
2. Set managing Permissions to auto
3. Run on the emulator

### Expected Behavior

As soon as the user taps 'Allow' the camera preview should be displayed

### Actual Behavior

Preview turns black instead. If the activity/app is re-entered, the camera works properly though, but this is bad for user experience.

**Comment by Zarkopafilis** [comment]
If the activity (or the fragment's activity) that holds the camera view listens for successful permission requests and then re-initializes the camera view, everything works properly, but this is a workaround.

**Comment by emersoncloud** [comment]
Hey @Zarkopafilis can you test on the latest version 1.0.0-beta1? This issue should be resolved there. If not report back and I can reopen this ticket. =)

**Comment by hiviiup** [comment]
Hey @emersoncloud ,I used 1.0.0-beta1.it's also black preview. 
![b56670b027fdc8f1eb93614ce8466987](https://user-images.githubusercontent.com/10386383/43631241-3c06ac3c-9735-11e8-90d1-11dbbb16a0c7.jpg)
![img_4095](https://user-images.githubusercontent.com/10386383/43631290-5e76a33a-9735-11e8-9283-f1f2d4503089.JPG)

**Comment by emersoncloud** [comment]
Hi @hiviiup what steps did you take to get this blacked preview? We have another issue #348 to track this, should be resolved shortly but comment there if you have any more feedback.

**Comment by barees63** [comment]
I'm having this exact issue also, after granting permission the (back) camera preview remains black, if I toggle between front & back camera it starts working.

Once the initial permissions have been granted the preview works correctly every time.

I have CameraKitView hosted in a fragment which is in a ViewPager.
