### ISSUE TITLE
Select From Gallery Show All Folder

### ISSUE THREAD

**Issue by muratYamann** [CameraKit/camerakit-android#333]
**Hi CameraKit Team,**

How to show all photo files when selected galery.

![whatsapp image 2018-03-12 at 15 17 38 1](https://user-images.githubusercontent.com/13666793/37283338-aacabbc0-2608-11e8-99f3-58d3dfa7155b.jpeg)
![whatsapp image 2018-03-12 at 15 17 38](https://user-images.githubusercontent.com/13666793/37283339-aaeee950-2608-11e8-9e7f-e7038966c1ec.jpeg)

**Comment by emersoncloud** [comment]
Hi @muratYamann Could you fill out an issue following our issue template? I'm not sure what the expected behavior is and what is actually happening. Thanks!

**Comment by emersoncloud** [comment]
Closing this issue. Let me know if you are still experiencing issues and I can reopen!
