### ISSUE TITLE
does this project allow to record video to removable micro sdcard?

### ISSUE THREAD

**Issue by anonym24** [CameraKit/camerakit-android#335]
does this project allow to record video to removable micro sdcard?

**Comment by austinkettner** [comment]
We currently don't have a documented way to control the save directory. It is coming in 1.x.

**Comment by austinkettner** [comment]
Please see: https://github.com/CameraKit/camerakit-android/issues/336 which I made to track this =)

**Comment by anonym24** [comment]
using ffmpeg recorder I had problems with it https://github.com/bytedeco/javacv/issues/839
