### ISSUE TITLE
ImagePicker

### ISSUE THREAD

**Issue by muratYamann** [CameraKit/camerakit-android#337]
**Hi  CameraKit Team ,**
 
I want select photo in gallery but  my gallery not show image.

Device : SONY XPERİA, OS  7.0 

![screenshot_20180315-130833](https://user-images.githubusercontent.com/13666793/37506957-6830df4a-28fd-11e8-8fae-e8b54a6a576c.png)

**Comment by emersoncloud** [comment]
Hi @muratYamann could you fill out our issue template so I can better diagnose your issue. I'll reopen this ticket once you have! =)
