### ISSUE TITLE
Activate Flash like native camera when I Take a picture

### ISSUE THREAD

**Issue by bard0x** [CameraKit/camerakit-android#345]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

Yes

### Environment
compile 'com.wonderkiln:camerakit:0.13.1'

### Steps to Reproduce

1. cameraView.setMethod(CameraKit.Constants.METHOD_STILL);
2. cameraView.setFlash(CameraKit.Constants.FLASH_ON);
3. click on Capture Button that invoke captureImage() method

### Expected Behavior

I would simulate the flash on pressing of the capture button like the native camera or like a comportment for the method standard when the property of the flash is setted to FLASH_ON.

### Actual Behavior

When I invoke the method captureImage() with the status of the flash setted to FLASH_ON the flash of my back-camera is not activating.

Thank's in advance and thank's for this project guys!

**Comment by ksc91u** [comment]
setMethod(CameraKit.Constants.METHOD_STANDARD) when flash light state is FLASH_ON

**Comment by austinkettner** [comment]
Please take a look at our 1.0.0 PR! =) This along with the documented methods, are entirely ready to be used!
