### ISSUE TITLE
Camera1.java line 128  com.wonderkiln.camerakit.Camera1.start

### ISSUE THREAD

**Issue by muratYamann** [CameraKit/camerakit-android#346]
**I m Use last version  :   compile 'com.wonderkiln:camerakit:0.13.1'**

> Fatal Exception: java.lang.RuntimeException: setParameters failed
>        at android.hardware.Camera.native_setParameters(Camera.java)
>        at android.hardware.Camera.setParametersSubCam(Camera.java:2553)
>        at android.hardware.Camera.startPreview(Camera.java:1081)
>        at com.wonderkiln.camerakit.Camera1.start(Camera1.java:128)
>        at com.wonderkiln.camerakit.CameraView$2.run(CameraView.java:266)
>        at android.os.Handler.handleCallback(Handler.java:739)
>        at android.os.Handler.dispatchMessage(Handler.java:95)
>        at android.os.Looper.loop(Looper.java:168)
>        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by emersoncloud** [comment]
@muratYamann I was not able to recreate your same issue. Could you attach your app level build.gradle file? As well as the file that is causing this error.

We are working hard on v1.0.0 release which includes a lot of bug fixes and performance improvement. Check out the PR here #318 where you can find details and how to get started with v1.0.0. You might want to try this instead, but I can help you get 0.13.1 up and running in the mean time. Thanks!
