### ISSUE TITLE
logo for CameraKit.

### ISSUE THREAD

**Issue by damahboy** [CameraKit/camerakit-android#350]
I am @damahsyari and I mean sending this message because I want to contribute to CameraKit. may be useful for his changes to a better direction, or not at all helpful but I have at least tried to give the best for CameraKit
![camerakit](https://user-images.githubusercontent.com/38080324/38686585-30df9ffa-3e64-11e8-819f-369dbaa1dd51.png)
Logo white and black
![hitam putih](https://user-images.githubusercontent.com/38080324/38686623-47095488-3e64-11e8-8736-a28979b7f5a4.png)

![damah line](https://user-images.githubusercontent.com/38080324/38686577-2753dc62-3e64-11e8-97e1-5e1b3e1854ab.png)

 best regard from @damahsyarii

**Comment by emersoncloud** [comment]
@damahboy Thanks for those designs! We are pretty well set with our current logos but I'll let you know if we end up using what you made for anything in the future!
