### ISSUE TITLE
Offer for some features

### ISSUE THREAD

**Issue by jaksab** [CameraKit/camerakit-android#354]
### Is this a bug report?

No

### I want to offer some features which will helps during development

1. Modern smartphones make very high quality and great photos. Camera 1 has an array of acceptable survey resolutions and is able to set any of the acceptable output image sizes. Now this functionality is encapsulated and always at the maximum, it would be very cool to manage the quality and most importantly - the resolution.
2. I got a strange behavior when I have the orientation of the screen = portrait in my manifest, but the activity with the camera that ages in the landscape orientation of the phone (although it's locked) strangely stretches the image in the viewfinder. Is it possible to add a manual camera orientation setting without the need to check the actual one. And it would be very good to have a listener orienting the camera for handling the UI components.

Thanks!

**Comment by emersoncloud** [comment]
@jaksab Thanks for the feature requests. I'll take this back to the team to review. I'll update you when we've added them to our milestones!
