### ISSUE TITLE
NullpointerException

### ISSUE THREAD

**Issue by ivanicsjozsef94** [CameraKit/camerakit-android#358]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

yes

### Environment
Android 7.0 Nokia

### Steps to Reproduce

(Write your steps here:)

1. Open camera.
2.  cameraView.captureImage(); is called.

(Write what happened. Add screenshots!)

### Reproducible Demo

takeImageButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if(cameraView != null) {
                    try {
                        cameraView.captureImage();
                    } catch (Exception e) {
                        Toast.makeText(PhotoBoothActivity.this, R.string.capture_image_error, Toast.LENGTH_LONG).show();
                    }
                }
            }
        });
![32644929_1664120026959028_2372673181375791104_n](https://user-images.githubusercontent.com/7083831/40133457-224f970a-5940-11e8-9c63-1596948867ed.png)

**Comment by emersoncloud** [comment]
Hi @ivanicsjozsef94 thanks for your issue. It looks like you're using CameraKit version 0.13.x. Very shortly we will officially move to v1.0.0, a much cleaner and more robust version of CameraKit. If you could give #318 a try and let me know if your issue persist that would be great!

**Comment by emersoncloud** [comment]
Closing issue. I'll open if you still are having problems!
