### ISSUE TITLE
Use the Front camera to take a picture, then Application fails to load image results.

### ISSUE THREAD

**Issue by rezamusic881** [CameraKit/camerakit-android#359]
#### Expected behavior
Be supposed, Take a picture with the front camera and use the "ckMethod feature in standard mode and cKcropOutput feature in false mode" works best.

#### Actual behavior
When I take a picture with the front camera and use the "ckMethod feature in standard mode and cKcropOutput feature in false mode". but the app does not load image data.

#### How to reproduce
You can get CameraKit Demo app on Playstore, When successfully installed the app:

1. Run the application
2. Make sure the setting "ckMethod feature in standard mode and cKcropOutput feature in false mode"
3. Please shoot with the front camera, Then the application failed to load the image.

***
***

* Browser : Redmi Note 5A
* System Operating : 7.1.0 Nougat
* App Version : 0.13.2

#### Recording Of The Bug
https://youtu.be/jX_c2tqQP6U

#### Proof Of Work Done
http://www.github.com/rezamusic881

**Comment by emersoncloud** [comment]
Hey @rezamusic881 thanks for the detailed issue. We are in the process of rolling out a significant overhaul to CameraKit, v1.0.0 on a PR here: #318, which will resolve this problem. 1.0.0 is currently stable and you can expect an official release by the end of the month!
