### ISSUE TITLE
Update "Capturing Video" docs on documentation website

### ISSUE THREAD

**Issue by mattlogan** [CameraKit/camerakit-android#361]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

Yes

The section in the docs for [capturing video](http://docs.camerakit.website/#/?id=capturing-video) appears to be out of date.

The `CameraView` class in version `0.13.2` doesn't appear to have any methods named `startRecording()`, `startRecordingVideo()`, `stopRecording()`, or `stopRecordingVideo()` (as the documentation suggests). Thanks!

**Comment by emersoncloud** [comment]
@mattlogan That was my fault. I mistakenly updated the docs to the v1.0.0 way of capturing images and video. I've reverted them to the 0.13.x methods. 

You might want to give 1.0.0 a go. It is the latest version of CameraKit and we will have an official release out very soon! It is stable in its current form. We've done a lot to improve the performance and functionality of CameraKit.
