### ISSUE TITLE
Camera1 Api set smallest picture size

### ISSUE THREAD

**Issue by tacttnysma** [CameraKit/camerakit-android#362]
### Is this a bug report?

Yes
In Camera1 api set always smallest size.
### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?
Yes

### Environment
Any device below api level 21

[I think change this line](https://github.com/CameraKit/camerakit-android/blob/v1.0.0/camerakit/src/main/java/com/camerakit/CameraKitView.java#L1352)

**Comment by emersoncloud** [comment]
Hey @tacttnysma thanks for bringing this to our attention. I just created a ticket #363 to set the image resolution. I'll add your issue there and we'll be sure to get this fixed when implementing that feature!
