### ISSUE TITLE
Didn't find class "android.support.media.ExifInterface"

### ISSUE THREAD

**Issue by zomll** [CameraKit/camerakit-android#371]
Didn't find class "android.support.media.ExifInterface"

**Comment by emersoncloud** [comment]
Hey @zomll please fill out an issue following our issue template so we can better diagnose what problem you're running into. Thanks!

**Comment by vuhung3990** [comment]
hi @zomll, did you `exclude group: 'com.android.support'` in file build.gradle, if yes you need to add 
`implementation 'com.android.support:exifinterface:27.1.1'`

**Comment by emersoncloud** [comment]
Hey @vuhung3990 thanks for clearing this up. @zomll I'll close this issue as it seems its not directly related to CameraKit. Let us know if you have any more problems, thanks!
