### ISSUE TITLE
Fail to connect to camera service

### ISSUE THREAD

**Issue by tank777** [CameraKit/camerakit-android#373]
Fatal Exception: java.lang.RuntimeException
Fail to connect to camera service

android.hardware.Camera.<init> (Camera.java:654)
android.hardware.Camera.open (Camera.java:495)
arrow_right
com.wonderkiln.camerakit.Camera1.openCamera (Camera1.java:667)
com.wonderkiln.camerakit.Camera1.start (Camera1.java:124)
com.wonderkiln.camerakit.CameraView$2.run (CameraView.java:266)
android.os.Handler.handleCallback (Handler.java:815)
android.os.Handler.dispatchMessage (Handler.java:104)
android.os.Looper.loop (Looper.java:194)
android.os.HandlerThread.run (HandlerThread.java:61)

Device 
Asus
Samsung
HUAWEI
Sony

Version : 0.13.1

**Comment by emersoncloud** [comment]
@tank777 Thanks for the issue. Could you try connecting to the Camera Service with CameraKit version 1.0.0? This will fix the issue you're seeing here. Check out the PR notes #318 for basic implementation details =)
