### ISSUE TITLE
Updated Documentation for v1.0.0

### ISSUE THREAD

**Issue by emersoncloud** [CameraKit/camerakit-android#374]
Create a new set of documentation for the upcoming 1.0.0 release. 

Official Maintainer Ticket: @emersoncloud

**Comment by Daksh14** [comment]
We are kinda clashing with this http://docs.camerakit.website/#/ and this [#318](https://github.com/CameraKit/camerakit-android/pull/318)

**Comment by austinkettner** [comment]
@Daksh14 Right now the only documentation valid is the content in the PR Notes. We are working to update the docs site to be fully reflective of 1.0.0 by Release

**Comment by Daksh14** [comment]
@austinkettner can i email you some errors where you can help?

**Comment by austinkettner** [comment]
@Daksh14 Yes, you can use austin at wonderkiln.com

**Comment by pinigtech** [comment]
Can I volunteer to help with the documentation?

**Comment by emersoncloud** [comment]
Hey @pinigtech thanks for the offer! I'll have you email austin at camerakit dot email and he can cover this in more detail.

**Comment by pinigtech** [comment]
Will do

**Comment by emersoncloud** [comment]
We have updated the documentation for each beta version on our new docs page, https://camerakit.io/docs. Let me know if you have any more concerns.
