### ISSUE TITLE
Question: Does camerakit solve the following important problems? 

### ISSUE THREAD

**Issue by akidee** [CameraKit/camerakit-android#375]
Does camerakit ...

* use camera1 instead of camera2 if device has hardware level legacy? This will be faster, and camera2 ignores camera1 string parameters.
* include a device database? This is needed to fix bugs made by manufacturers.
* fix things from the ground up, i. e. fixing the native APIs itself?

**Comment by emersoncloud** [comment]
Hi @akidee thanks for your questions. We will be sure to take these into consideration for future builds. Currently we do not have a device database or fix the native APIs themselves, but we do switch between camera1 and camera2 depending on API level. =)
