### ISSUE TITLE
CameraView not close on .close();

### ISSUE THREAD

**Issue by Trusted97** [CameraKit/camerakit-android#379]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?
No, I will not be there

### Environment
Camera Kit version : 0.13.1
Android 7.0 Api 24 (Samsung Galaxy S7 (SM-G930F) 

### Steps to Reproduce

1. Create an Activity with a CameraView and another activity without it
2. On second activity pass a int value in intent in first activiy get value with getIntent and if val > 0 close/release the camera

### Expected Behavior

The camera should be released 

### Actual Behavior

The value is correctly passed, because other code inside the if  statement work well but 
`CameraView.close();` doesn't work  the camera is still open

### Reproducible Demo

w.i.p

**Comment by austinkettner** [comment]
Hey @Trusted97 give this a test on 1.0.0 via #318, let me know if this issue still exists!

**Comment by Trusted97** [comment]
Hi @austinkettner where can i found Constants in 1.0.0 version?

**Comment by austinkettner** [comment]
Can you elaborate on what you mean @Trusted97 ?

**Comment by Trusted97** [comment]
The constants about Method,Flash,VideoQuality...
`CameraKit.Constants.METHOD_STILL;`
