### ISSUE TITLE
Point of setting a fixed size for SurfaceHolder

### ISSUE THREAD

**Issue by SmartToolFactory** [CameraKit/camerakit-android#407]
Why do you use getSurfaceHolder().setFixedSize(getPreviewWidth(), getPreviewHeight()); since it has no effect on preview size as pointed [here](https://github.com/google/cameraview/blob/master/library/src/main/api9/com/google/android/cameraview/SurfaceViewPreview.java).

It's not actually issue but i don't get why setting fixed size for SurfaceHolder is necessary with
```
   void setPreviewParameters(final int width, final int height, final int format) {
        super.setPreviewParameters(width, height, format);
        mContainer.setPreviewSize(new Size(width, height));
        mContainer.post(new Runnable() {
            @Override
            public void run() {
                getSurfaceHolder().setFixedSize(getPreviewWidth(), getPreviewHeight());
                System.out.println("SurfaceViewPreview POST Preview width: "
                        + getPreviewWidth() + ", height: " + getPreviewHeight() + ", format: " + format);
            }
        });
    }
```

I also tested it with Grafika code and it only improves resolution for OpenGL drawing and the code [here](https://github.com/google/cameraview/blob/master/library/src/main/api9/com/google/android/cameraview/SurfaceViewPreview.java) isn't using it either, is there something i'm missing?

**Comment by emersoncloud** [comment]
@SmartToolFactory thanks for the deep dive into this issue. The issue pertains to CameraKit version 0.13.2. Our current development focus is on v1.0.0 but we will address this in a future patch of 0.13.x.
