### ISSUE TITLE
Cannot CaptureVideo

### ISSUE THREAD

**Issue by danhnexle** [CameraKit/camerakit-android#408]
### Is this a bug report?
(write your answer here)
Yes

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

(Write your answer here.)
Yes
### Actual Behavior

(Write what happened. Add screenshots!)
I cannot capture video in 0.13.2. When I call capture video, the camera call release() immediately and do not run in call back.

**Comment by langhoangal** [comment]
Same here, use the latest version. It work on my android 5, but not working on android 8

**Comment by ManojMM026** [comment]
this is basic! it is not working for me either. Samsung galaxy s8 with Oreo.
 Now I may have to go and do it all from scratch.

**Comment by langhoangal** [comment]
@ManojMM026 after handling WRITE_EXTERNAL_STORAGE by myself then it works. You can give a try.

**Comment by emersoncloud** [comment]
Closing. If it is still an issue let me know and I can reopen.
