### ISSUE TITLE
Request permission handling

### ISSUE THREAD

**Issue by iad24** [CameraKit/camerakit-android#411]
At first, the camera view of my screen is hidden. Then if a user clicks a button, I will then show the camera and along with the permission request dialog. Whats happening now is that when I open the screen and even if my camera is still hidden, it will already ask for permission. Is it possible that we can control when to ask the permission? or disable the auto handling of this permission from the lib so we can request them ourselves?

**Comment by emersoncloud** [comment]
Hi @iad24, sorry for the late response. CameraKit should only request permissions when the CameraKitView is started with the `onStart()` method. Closing this ticket for now. Let me know if you're still encountering issues and I'll be glad to reopen!
