### ISSUE TITLE
I cant record video , the callback not be called 

### ISSUE THREAD

**Issue by yankelandroid** [CameraKit/camerakit-android#413]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?
YES

### Environment

com.camerakit:camerakit:1.0.0-Snapshot

### Steps to Reproduce
1. if i want record video , camerakitview.startVideo(); than camerakitview.stopVideo();
and implement  cameraView.captureVideo(new CameraKitView.VideoCallback() {
                    @Override
                    public void onVideo(CameraKitView cameraKitView, Object o) {

                        Toast.makeText(getContext(), "start", Toast.LENGTH_SHORT).show();
                    }
                });
But nothing happened ...

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by emersoncloud** [comment]
Hi @yankelandroid video has not yet been implemented in v1.0.0-betaX.X. We are looking to roll that out with v1.0.0-beta4.0 in about a week. Stay tuned for that release, we'd love to get your feedback on video performance then!

**Comment by HBiSoft** [comment]
> We are looking to roll that out with v1.0.0-beta5 shortly. Stay tuned for that release

8 Months later still in beta 3?
