### ISSUE TITLE
Documentation is hopelessly out of date

### ISSUE THREAD

**Issue by bpappin** [CameraKit/camerakit-android#416]
The documentation is so out of date, its pretty useless.
See:
http://docs.camerakit.website/#/

**Comment by austinkettner** [comment]
Rest assured it's not hopeless!

It's a known area we need to improve vastly, we are waiting on Beta4 with it's final API. After that we will be rapidly improving the documentation around v1.0.0.

The documentation is entirely aimed at 0.13.x and for that release it is up to date!

**Comment by ArslanKathia** [comment]
when the new Version of camera-Kit is released?

**Comment by austinkettner** [comment]
Hey all, we expect to be rolling out a new documentation site and proper documentation for the various current releases of CameraKit within the next two weeks.

**Comment by usmanrana07** [comment]
@austinkettner  when is new documentation or new major version expected as few months in wait.
