### ISSUE TITLE
Does video capture work for 1.0.0 beta?

### ISSUE THREAD

**Issue by tt-aali** [CameraKit/camerakit-android#418]
### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by emersoncloud** [comment]
@tt-aali video has not yet been implemented in v1.0.0-betaX.X. We are looking to roll that out with v1.0.0-beta5 shortly. Stay tuned for that release, we'd love to get your feedback on video performance then!
