### ISSUE TITLE
How to use getFrames version 1.0.0

### ISSUE THREAD

**Issue by EdwardTeac** [CameraKit/camerakit-android#419]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

Yes

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

Im using the following code to catch frames, and share camera preview
cameraKitView.captureFrame(new CameraKitView.FrameCallback() {
                    @Override
                    public void onFrame(CameraKitView cameraKitView, byte[] bytes) {

                        bitmap = BitmapFactory.decodeByteArray(bytes , 0, bytes.length);
                        cameraFrames.setImageBitmap(bitmap);
                    }
                });

But it doesn display anything :(

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by emersoncloud** [comment]
Like @XinyueZ mentioned, please follow up on ticket #342 for frame inspection updates. Closing this ticket.

**Comment by johcam12** [comment]
@emersoncloud #342 points back to this issue (https://github.com/CameraKit/camerakit-android/issues/342#issuecomment-424252674) which makes this issue non GC-collectable.

**Comment by RahulRawat95** [comment]
Is this implemented yet?

**Comment by rohfosho** [comment]
@dwillmc Any updates on when `captureFrame` will be implemented?

**Comment by Zaniyar** [comment]
@rohfosho I don't think it will ever be implemented.
