### ISSUE TITLE
How to set the size of the preview window?

### ISSUE THREAD

**Issue by liusilong** [CameraKit/camerakit-android#420]
**How to set the size of the preview window? Because I want to take a photo with a ratio of 1:1 or 3:4.**
I want to call the following method settings，
```java
void setPreviewParameters(int width, int height, int format) {
        this.mPreviewWidth = width;
        this.mPreviewHeight = height;
        this.mPreviewFormat = format;
    }
```
But I can't call it.
Thanks !!!

**Comment by liusilong** [comment]
Ok! When I set this property `camerakit:ckCropOutput="true"` the photo taken is the same as the preview image.

**Comment by SohailZahidGit** [comment]
@liusilong `camerakit:ckCropOutput="true"` in case of video is stretching the video in full screen mode.

**Comment by emersoncloud** [comment]
Hi @liusilong closing this issue. Let me know if you have any more questions! =)

**Comment by TrentPierce** [comment]
> camerakit:ckCropOutput="true"

Where does this go?
