### ISSUE TITLE
[FEATURE]Need clearCameraKitListener()

### ISSUE THREAD

**Issue by XinyueZ** [CameraKit/camerakit-android#422]
Is there any chance to do `removeCameraKitListener`  or similar?
If not, I want to make a PR for this feature.

**Comment by austinkettner** [comment]
@XinyueZ What is your end goal here? Can you explain the rationale behind requesting this feature? We can definitely look at adding it =)

**Comment by XinyueZ** [comment]
This is for the integrity of the API, since with "add" there should be a "remove" as a matter of course, and there is no guarantee that the added listeners will be called incorrectly without control. What do you think?

**Comment by bpappin** [comment]
I think I would +1 this if its not too hard to add, if not just for symmetry, I could see using it now and then.

**Comment by emersoncloud** [comment]
Merged in #448. Closing this issue.
