### ISSUE TITLE
Capture video not working

### ISSUE THREAD

**Issue by ManojMM026** [CameraKit/camerakit-android#423]
### Is this a bug report?

YES.

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

(Write your answer here.)

### Environment
    implementation 'com.wonderkiln:camerakit:0.13.1'

### Steps to Reproduce

(Write your steps here:)

1. capture video with `camera.captureVideo(file, callback)`
2. Log printed as
```

D/ViewRootImpl@b026d7c[CustomCamera]: ViewPostIme pointer 0
D/ViewRootImpl@b026d7c[CustomCamera]: ViewPostIme pointer 1
I/MediaRecorderJNI: setup
I/MediaRecorderJNI: setAudioSource(5)
I/MediaRecorderJNI: setVideoSource(1)
I/MediaRecorderJNI: setVideoFrameRate(30)
I/MediaRecorderJNI: setVideoSize(720, 480)
I/MediaRecorderJNI: setParameter()
    setVideoEncoder(2)
I/MediaRecorderJNI: setParameter()
I/chatty: uid=10359(u0_a359) com.bluestreamdigital.gap identical 1 line
I/MediaRecorderJNI: setParameter()
    setAudioEncoder(3)
I/MediaRecorderJNI: setParameter()
I/MediaRecorderJNI: setOutputFile
I/MediaRecorderJNI: prepare
    get_surface
    prepare: surface=0x77c34fe000
I/MediaRecorderJNI: start
D/ViewRootImpl@b026d7c[CustomCamera]: ViewPostIme pointer 0
D/ViewRootImpl@b026d7c[CustomCamera]: ViewPostIme pointer 1
I/MediaRecorderJNI: native_reset
I/MediaRecorderJNI: release
I/Choreographer: Skipped 47 frames!  The application may be doing too much work on its main thread.

```

### Expected Behavior
Should capture video and store it on sd card. 

(Write what you thought would happen.)

### Actual Behavior
May be recording but not writing output to file and not even firing callback

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by ManojMM026** [comment]
Samsung s8 with oreo 8.0.0

**Comment by DavidAngelos** [comment]
@ManojMM026 have you gave your app the write external storage permission?

**Comment by ManojMM026** [comment]
Yes

**Comment by austinkettner** [comment]
Hey everyone, we are no longer supporting 0.13.x with active development and instead focused on our v1.00 via #318 - video functionality doesn't exist currently but it's coming soon.

**Comment by sarthak-m** [comment]
Hey Austin, is the video functionality added since then? If not, when can we expect that?
