### ISSUE TITLE
MediaRecorder delay

### ISSUE THREAD

**Issue by kingstone59** [CameraKit/camerakit-android#43]
The record start with delay when call `mMediaRecorder.start()`

**Comment by platinum7919** [comment]
anyone managed to find a solution for this?

**Comment by emersoncloud** [comment]
Hi @platinum7919 what issue are you experiencing?

**Comment by kingstone59** [comment]
The only way to record video is to use `MediaEncoder` like [https://github.com/saki4510t/AudioVideoRecordingSample](this)

**Comment by Timone** [comment]
Thanks @kingstone59 , your link is busted though, should be `[text](url)`

**Comment by emersoncloud** [comment]
Hi @kingstone59 We currently do not have video support in 1.0.0 but we are adding that next so expect it soon! I'll report back here when it is implemented.
