### ISSUE TITLE
No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

### ISSUE THREAD

**Issue by letruonglamit** [CameraKit/camerakit-android#436]
Deprecated functions
Seems "mips64el-linux-android" is missing because it got deprecated. So I can not build

![image](https://user-images.githubusercontent.com/22797715/46806167-220c8d00-cd91-11e8-9c86-181499fad98c.png)

**Comment by ckdvivedi** [comment]
Update to latest

classpath 'com.android.tools.build:gradle:3.2.1'
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip

**Comment by emersoncloud** [comment]
Thanks for suggestion @ckdvivedi! Closing this ticket.
