### ISSUE TITLE
3.9 beta -- camerakitview.captureimage/capturevideo

### ISSUE THREAD

**Issue by tt-aali** [CameraKit/camerakit-android#437]
Do those callbacks still exist? Or are we capturing snapshots and videos in a different way?

**Comment by emersoncloud** [comment]
Hi @tt-aali we will update the documentation to reflect the latest changes in 1.0.0 when we release beta4. The `camerakitview.captureImage` method still exists and expects a `CameraKitView.ImageCallback()`. See the example below:

```
cameraKitView.captureImage(new CameraKitView.ImageCallback() {
                @Override
                public void onImage(CameraKitView cameraKitView, final byte[] photo) {
                     // do something with the photo
                }
}
```

Currently `captureVideo` is empty but will exist in 1.0.0-beta5!

**Comment by fahime-ghasemi** [comment]
How can we take video when we are using 1.0.0-beta3.9?
