### ISSUE TITLE
Image Texts getting reversed in case of front camera.

### ISSUE THREAD

**Issue by ArmnDev** [CameraKit/camerakit-android#445]
I am trying to take photo with front camera and its working fine but the texts in the imaae are getting reversed.    
### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by austinkettner** [comment]
Hi @ArmnDev can you please follow the issue template and we will reOpen this?
