### ISSUE TITLE
Camera preview is very different than the native camera app v1.0.0

### ISSUE THREAD

**Issue by abhinav011085** [CameraKit/camerakit-android#451]
was working fine in 0.13.0

Native camera image
![img_20181113_120031287](https://user-images.githubusercontent.com/15052440/48395103-26371c00-e73c-11e8-9241-c64b7fe77f41.jpg)
Camerakit's camera image
![pic1542090617467](https://user-images.githubusercontent.com/15052440/48395104-26371c00-e73c-11e8-959c-75e863b6bd53.png)

**Comment by emersoncloud** [comment]
Thanks for creating this issue! Could you provide some more information to help us get to the bottom of this?

1. CameraKit Version (which v1.0.0 beta version are you using)
2. Android Device
3. Android Version
4. XML code where you create the CameraKitView 
5. And how you initialize the CameraKitView in Java

**Comment by austinkettner** [comment]
Can you share your gradle implementation @abhinav011085 ? It still not clear which exact version of CameraKit you are using.

**Comment by abhinav011085** [comment]
implementation group: 'com.camerakit', name: 'camerakit', version: '1.0.0-Snapshot', changing: true

**Comment by emersoncloud** [comment]
Could be related to #470.

@abhinav011085 could you try on the latest release, `v1.0.0-beta3.10` and report back if the issue persists?

**Comment by emersoncloud** [comment]
Any word on results from latest beta, `v1.0.0-beta3.11`? Closing this issue for now. Comment back if you're still encountering issues.
