### ISSUE TITLE
How i can use version v0.13.4?

### ISSUE THREAD

**Issue by mnayef95** [CameraKit/camerakit-android#480]
How i can use version v0.13.4?
i tried 

`implementation 'com.camerakit:camerakit:0.13.4'`

but it's doesn't work

**Comment by emersoncloud** [comment]
To use v0.13.4, the gradle line is: 

```implementation 'com.wonderkiln:camerakit:0.13.4'```

The `v0.13.X` line is under `wonderkiln` and the new `v1.0.0-betaX` releases are all under `camerakit`. Sorry for the confusion!

**Comment by KryptKode** [comment]
Can this be included in the documentation? It could be confusing.

**Comment by snaqviAndroidApp** [comment]
Hi 

I am trying to use video recording api available (if any), however getting the following situation: 

I am getting the following when trying in both of these: 

1. implementation 'com.camerakit:camerakit:0.13.4'  (error: not able to resolve... )
2. implementation 'com.camerakit:camerakit:1.0.0-0.13.4' (same error)

more in the docs (https://camerakit.io/docs), no matter what version I choose: the docs are shown for: 1.0.0-beta3.11


Please if it could be helped

regards

**Comment by rahadurr** [comment]
> To use v0.13.4, the gradle line is:
> 
> `implementation 'com.wonderkiln:camerakit:0.13.4'`
> 
> The `v0.13.X` line is under `wonderkiln` and the new `v1.0.0-betaX` releases are all under `camerakit`. Sorry for the confusion!

Thanks It's work for me..

**Comment by PetroHrynyuk** [comment]
Failed to resolve: com.wonderkiln:camerakit:0.13.4
