### ISSUE TITLE
huawei mate9 pro 拍照花屏

### ISSUE THREAD

**Issue by bluesky0506** [CameraKit/camerakit-android#482]
### Is this a bug report?

华为mate9pro打开拍照页面，花屏。无法使用。必显，谢谢！

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by emersoncloud** [comment]
Hi @bluesky0506 I'm having trouble understanding your issue. I quick popped your message into Google translate and read: "Huawei mate9pro opens the photo page and spends the screen. Not available. Must show, thank you!"

Which version of CameraKit are you using? Could you send us a log of any errors you're getting and we might be able to help! Closing this issue for the time being.
