### ISSUE TITLE
    java.lang.RuntimeException: takePicture failed

### ISSUE THREAD

**Issue by RahilRK** [CameraKit/camerakit-android#490]
### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by emersoncloud** [comment]
Hey @RahilRK thanks for the issue. Could you fill out the issue template there and provide us the following information:
1. CameraKit version
2. Android Device information

Closing this issue until then, thanks!
