### ISSUE TITLE
demo still using import com.wonderkiln.camerakit.CameraKit

### ISSUE THREAD

**Issue by Xenorage** [CameraKit/camerakit-android#493]
### Is this a bug report?
yes

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

no
### Steps to Reproduce

In Demo MainActivity.java and CameraControls.java there are imports what still using wonderkiln in imports
import com.wonderkiln.camerakit.CameraKit;
import com.wonderkiln.camerakit.CameraView;
import com.wonderkiln.camerakit.core.BuildConfig;

### Expected Behavior
import com.camerakit.CameraKit;
...

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by emersoncloud** [comment]
Hey @Xenorage thanks for the heads up. That demo application is based on 0.13 (`com.wonderkiln:camerakit`) rather than the v1.0.0-beta releases (`com.camerakit:camerakit`). Once we release the official 1.0.0 we will update the demo application to match.
