### ISSUE TITLE
Add coroutines in the my module

### ISSUE THREAD

**Issue by rviannaoliveira** [CameraKit/camerakit-android#496]
Hi,

I updated the version 0.13x to new API, but I thought strange I have to add the `org.jetbrains.kotlinx:kotlinx-coroutines-android` in my module. Could you avoid it and put inside of the lib?

**Comment by emersoncloud** [comment]
Hey @rviannaoliveira. Thanks for the question. We're going to be moving away from Kotlin in the official v1.0.0 release of CameraKit. So for now, it's required in the beta versions but won't be in the official release!

**Comment by rviannaoliveira** [comment]
when Will the release be enabled?
