### ISSUE TITLE
can I set default values before camera starting programically?

### ISSUE THREAD

**Issue by dphans** [CameraKit/camerakit-android#50]
For example, If I need to set default camera is front before camera start, can I do that?
(I impossible to change layout xml attributes, because user can change default camera in settings, I stored it in SharedPreferences instance).

**Comment by mbernr** [comment]
Please take a look at the README:

`cameraView.setFacing(CameraKit.Constants.FACING_FRONT);`

**Comment by luongvo** [comment]
@dphans Take a look at all public methods inside `CameraView` object.

**Comment by dphans** [comment]
@mbernr @luongvo I see. But when call `startCamera` method after `setFacing`, camera facing not correct update.
I've fixed temporary by this way (set default in layout file):
- In layout file: add 2 CameraView elements, one CameraView setup it default front-facing, one for back-facing.
- In activity: get user settings and select one in 2 CameraView to show on screen.

I think this is temporary fixed for company project, but can close this issue. Many thanks.
