### ISSUE TITLE
When will cameraKit become stable?

### ISSUE THREAD

**Issue by wellbranding** [CameraKit/camerakit-android#500]
Hello, we use another camera library in the production, but we are interested in switching to your solution. We have tested it, and it works well! The only problem is the fact that library is in beta... And our clients are not willing for using dependencies in beta, It also devalues our solution. I Would like to know the expected dates.

**Comment by UmarBhutta** [comment]
Hi, i don't think beta is a bad option because we are using it for one of our client with more than 25k monthly users.

**Comment by rviannaoliveira** [comment]
I'm interested about it too.

**Comment by emersoncloud** [comment]
Hey @rviannaoliveira sorry for the delay. We got the same question in [spectrum.chat](https://spectrum.chat/?t=feed2ae2-aa28-4e51-83f2-2f6615682850) and answered it there. Here's what Austin wrote:


This is something we are super focused on, but is proving to be difficult to accurately predict. We have a lot of production apps using CameraKit, but absolutely understand your situation regarding the Beta tag. Let us dig into this a bit more and I will give you an accurate expectation soon.

**Comment by rviannaoliveira** [comment]
tks
