### ISSUE TITLE
Camera preview black after initial permissions grant

### ISSUE THREAD

**Issue by barees63** [CameraKit/camerakit-android#542]
After granting permission the (back) camera preview remains black, if I toggle between front & back camera it starts working.

Once the initial permissions have been granted the preview works correctly every time.

I have CameraKitView hosted in a fragment which is in a ViewPager.  All lifecycle
events are being forwarded to camera-kit in the fragment.

This is reproducible in both simulator and physical devices, so far only tested on Android 9.

Using beta3.10

**Comment by barees63** [comment]
OK, this issue for me was that the permissions result was being sent to the activity and I had to manually forward it to the fragment hosting the camera.

**Comment by abhilasha3297** [comment]
@barees63 how did you go about it?
