### ISSUE TITLE
LG G3 video results are somehow distorted

### ISSUE THREAD

**Issue by glocci** [CameraKit/camerakit-android#59]
I tried different devices, and I found that on the lg g3 the video is recorded deformed on the height :(

**Comment by mbernr** [comment]
I have the same issue with the LG K8. On other devices it appears to work fine.

**Comment by Ninjaman494** [comment]
I have the same problem on the Samsung Galaxy S4. The video is cropped incorrectly so there are black bars on the top and bottom. I tried `ckCropOuput=true` in the XML but that didn't seem to make a difference.

**Comment by Ninjaman494** [comment]
Good new, I was able to fix the problem by setting `ckVideoQuality=max720p`. I did this in the XML, but I don't see why it wouldn't work programmatically. See if this works on your devices too.
