### ISSUE TITLE
Failed to resolve: com.camerakit:camerakit:0.13.X

### ISSUE THREAD

**Issue by mcnarek** [CameraKit/camerakit-android#617]
I want to use camera with older kit but here i got 

![image](https://user-images.githubusercontent.com/5946745/95025011-b582ab00-0697-11eb-8f4b-f4096734133e.png)

**Comment by mcnarek** [comment]
Sorry I used Cemarakit instead of wonderkiln

**Comment by YYKKKKXX** [comment]
Hi, I use woderkiln, but I still have that problem.
How did you succeed?
