### ISSUE TITLE
Video Not Sharing on Facebook

### ISSUE THREAD

**Issue by ahsanhayat092** [CameraKit/camerakit-android#74]
Hi, I am trying to share the video made with this kit but it gives an error.
In case of massenger it says "Sorry, Massenger was unable to process this video". While for FACEBOOK the video never shows up.  Can you please help?

Here is my code that I am using for sharing:

                   Intent share = new Intent(Intent.ACTION_SEND);
                    share.setType("video/*");
                    String path = videoFile.getPath();
                    Uri videoUri = Uri.parse(path);
                    share.putExtra(Intent.EXTRA_STREAM, videoUri);
                    startActivity(Intent.createChooser(share, "Select"));

**Comment by palaciosyansro** [comment]
Are you able to share it through other options? like email or whatsapp
