### ISSUE TITLE
video recorded in landscape mode not being read as landscape

### ISSUE THREAD

**Issue by palaciosyansro** [CameraKit/camerakit-android#75]
Hi! I'm trying to make my camera able to record videos in portrait and landscape mode. I haven't been able to achieve that yet. When recording in landscape, the video twists in this unusual way, and I haven't found any parameter to set it as landscape.
Wonder if any of you dealed with this issue. 
Just for the record, I've read EVERY issue here and none of those contain any solution for my prob.
I'm also attaching some screenshots to show you how it behaves.
![screenshot_2017-04-24-15-36-13](https://cloud.githubusercontent.com/assets/27975732/25357646/f7f9833c-2914-11e7-9787-e10699fd6606.png)

Thanks!

**Comment by L3K0V** [comment]
I have same issue. Is there any workaround or something like this?

**Comment by eomine** [comment]
I had the same problem. See my PR: #111
