### ISSUE TITLE
how to custom video's width and height when capture video?

### ISSUE THREAD

**Issue by dabaooline** [CameraKit/camerakit-android#79]
how to custom video's width and height when capture video? thank you

**Comment by snc001** [comment]
I also would like to know this - when its captured to have the same custom aspect ratio that was set on the view finder

**Comment by Mack4545** [comment]
I would like this too. The images are sized as per the camera view, however the video is full screen height + width every time.

**Comment by MuhammedRefaat** [comment]
why closing it? there is no solution to that yet
