### ISSUE TITLE
Why stop isn't called in another thread but start is.

### ISSUE THREAD

**Issue by programmerr47** [CameraKit/camerakit-android#92]
As I know, the class `CameraView` has two main method that must be called before/after work with it: `start()` and `stop`. 

If we go to implementation of these functions we will see, that `start` method contains: 
```java
new Thread(new Runnable() {
    @Override
    public void run() {
        mCameraImpl.start();
    }
}).start();
```

but `stop` method contains only `mCameraImpl.stop();`

So for first method the new tread is started, but for the second isn't.
My question is "why"? Because it seems, that `stop` method requires pretty big amount of time.

You see, I want to have a list of photos, and first element is `CameraView` with camera preview (like in Telegram application). I starting `CameraView` in `onViewAttachedToWindow` method, and stop it in `onViewDetachedFromWindow`. And my application lags when I scroll my list exactly in the moment when first item with camera preview fades from phone window.

**Comment by Johnson145** [comment]
I'm also having issues caused by this code part. The problem is, that `.stop()` may be called and executed in the main thread before `.start()` has finished in the separate thread. This results in an app crash as soon as the camera is used the next time.
