### ISSUE TITLE
Camera is on tablet stretched out

### ISSUE THREAD

**Issue by joeykieboom** [CameraKit/camerakit-android#96]
this is the tablet version, its stretched out...
![screenshot_2017-05-24-14-06-16](https://cloud.githubusercontent.com/assets/11156397/26403035/f2f14782-408c-11e7-8490-0ceb3a64d097.png)

this is the phone version, it looks pretty good..
![screenshot_20170524-142511](https://cloud.githubusercontent.com/assets/11156397/26403017/e5ad3892-408c-11e7-9110-ca302fd0439f.png)

I have no idea what makes it do this, is there anybody who can help me?

EDIT:

Its only in the preview! when I capture the photo, its result will be a normal sized photo

**Comment by joeykieboom** [comment]
bump

**Comment by Mattimon** [comment]
I've got the same problem. I use different tablets for testing and on both android 6.0 tablets i got this issue. the one with android 4.2.2 is working pretty well. could it be a problem with the camera2 api?
`<com.flurgle.camerakit.CameraView xmlns:camerakit="http://schemas.android.com/apk/res-auto"
                android:id="@+id/camera"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                camerakit:ckFacing="front"
                android:adjustViewBounds="true" />`

**Comment by tartacutza** [comment]
I face something similar when I open my camera activity (which is android:screenOrientation="sensorLandscape") and the phone is vertical when this starts. If I rotate my phone to landscape before or simply close and reopen the screen, the camera if refreshed and the stretching disappears.
